name: Discord Notification

on: 
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  notification:
    runs-on: ubuntu-20.04
    steps:
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          details: Tests Succeeded!
          text: A new version of Pokedex deployed
          description: to https://full-pokedex.onrender.com/ by ${{ github.actor }}
          webhookUrl: https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949

    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          details: Test Failed!
          text: Build failed
          description: commit ${{ github.sha }} by ${{ github.actor }} broke the build
          webhookUrl: https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949
